---
- name: ensure development libraries are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - libdb6.0-dev
    - libgdbm-dev
    - libssl-dev
    - libsqlite3-dev
    - libyaml-dev
    - mongodb-dev
    - tcl-dev
    - tk-dev
