---
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: centos6.yml
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "6"

- include: centos7.yml
  when: ansible_distribution == "CentOS" and
        ansible_distribution_major_version == "7"
