---
- name: ensure python virtualenv packages are installed
  apt: 
    pkg: "{{ item }}" 
    state: latest 
    update_cache: yes 
    cache_valid_time: 600
  with_items:
    - python-pip
    - python-virtualenv
    - virtualenv-clone
    - virtualenvwrapper

- name: ensure link to virtualenvwrapper.sh exists
  file:
    path: /usr/bin/virtualenvwrapper.sh
    src: /usr/share/virtualenvwrapper/virtualenvwrapper.sh
    state: link
